apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinerate-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinerate-api-gateway
  template:
    metadata:
      labels:
        app: cinerate-api-gateway
    spec:
      containers:
      - name: api-gateway
        image: cinerate/api-gateway:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cinerate-api-gateway-svc
spec:
  type: ClusterIP
  selector:
    app: cinerate-api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
