apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinerate-watchlist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinerate-watchlist-service
  template:
    metadata:
      labels:
        app: cinerate-watchlist-service
    spec:
      containers:
      - name: watchlist-service
        image: cinerate/watchlist-service:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cinerate-watchlist-service-svc
spec:
  type: ClusterIP
  selector:
    app: cinerate-watchlist-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
