name: CineRate CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    strategy:
      matrix:
        service:
          - api-gateway
          - user-service
          - review-service
          - watchlist-service
    steps:
      - uses: actions/checkout@v4
        continue-on-error: false
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
        continue-on-error: false
      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.service }}
        continue-on-error: false
      - name: Run tests
        run: npm test
        working-directory: ${{ matrix.service }}
        continue-on-error: false
